# Generated by Django 5.0.6 on 2024-07-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
